### ISSUE TITLE
詢問迷你課程公布欄的圖片規格

### ISSUE THREAD

**Issue by PoMingChen** [ntpuecon/minicourses#1]
@tpemartin @danielwu951219 嗨老師，子行，我有新增[2018-03-23-Basic-Web-skills](https://github.com/ntpuecon/minicourses/blob/master/_posts/2018-03-23-Basic-Web-skills) 和 [2018-03-24-Bootstrap](https://github.com/ntpuecon/minicourses/blob/master/_posts/2018-03-24-Bootstrap.md)

可是後者沒有辦法轉換出來，網址好像也不會產生底下一線，想要請你們幫我看看＠＠ 我覺得可能是因為我所附的CSS3_HTML5.png太大或者某些地方有問題？

Bootstrap那堂課已經ok，該圖片是google圖庫標示為可作為非商業用途再利用，所以沒問題。

**Comment by danielwu951219** [comment]
@PoMingChen ，你只是忘了將前者的檔案補上副檔名(.md或.html)，我已經幫你改好並sync囉~

**Comment by PoMingChen** [comment]
感恩，我想再問一下，是不是Jekyll自動sync需要一點點時間？（還是有某一個按鍵可以使用，立刻sync）

**Comment by tpemartin** [comment]
@PoMingChen Jekyll更新有時需要一些時間。如果你在本機 $ jekyll serve 沒問題，耐心等一下github就會出現——除非你另外加了github不支援的plugins。
